name: CI - Запуск тестов

on:
  push:
    branches: [ main, dev, fix ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Проверить код
        uses: actions/checkout@v4
      
      - name: Установить Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Установить Chrome и ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: '119.0.6045.105'  # Стабильная версия
      
      - name: Запустить ChromeDriver в фоне
        run: |
          chromedriver --version
          chromedriver --url-base=/wd/hub &
      
      - name: Установить зависимости
        run: npm ci
      
      - name: Запустить тесты
        run: npm test
        env:
          CI: true